### ISSUE TITLE
Mana_Core_Helper_Data::isManadevPaidLayeredNavigationInstalled() undefined

### ISSUE THREAD

**Issue by rugbymauri** [manadev/Mana_Filters#7]
Fatal error: Call to undefined method Mana_Core_Helper_Data::isManadevPaidLayeredNavigationInstalled() in ......./code/Model/Filter/Category.php on line 400

**Comment by vernard** [comment]
I have updated the module. Thank you for pointing this out.

Please perform a composer update on your project. (or git pull on dependent modules)
